meta:
  crop_size: 518       
  model: 'dinov2'  
  pred_depth: 6            
  pred_emb_dim: 384        
  use_bfloat16: false      

checkpoint_path: 'path/ckpt'

data:
  img_path: 'path/img'
  dataset: mvtec                        
  classnames:                            
    - bottle
    - cable
    - capsule
    - carpet
    - grid
    - hazelnut
    - leather
    - metal_nut
    - pill
    - screw
    - tile
    - toothbrush
    - transistor
    - wood
    - zipper

logging:
  folder: 'path/save'     
  write_tag: AD              

testing:
  K_top: 10           
  expect_fpr: 0.3     
  max_steps: 200      
  segmentation_vis: True   