meta:
  crop_size: 512       
  model: 'dinov3'  
  pred_depth: 6            
  pred_emb_dim: 384        
  use_bfloat16: false
  if_pred_pe: false    

checkpoint_path: 'logs/dinov3/train-step1950.pth.tar'

data:
  img_path: '/media/ymxlzgy/Data21/xinyan/mvtec'
  dataset: mvtec                        
  classnames:                            
    - bottle
    - cable
    - capsule
    - carpet
    - grid
    - hazelnut
    - leather
    - metal_nut
    - pill
    - screw
    - tile
    - toothbrush
    - transistor
    - wood
    - zipper

logging:
  folder: 'logs/dinov3/eval'     
  write_tag: AD              

testing:
  K_top: 10           
  expect_fpr: 0.3     
  max_steps: 200      
  segmentation_vis: True   