# @package app
meta:
  model: 'dinov3'  
  crop_size: 512 
  pred_depth: 6            
  pred_emb_dim: 384        
  use_bfloat16: false
  if_pred_pe: false    

dataset_name: ${data.data_name}

ckpt_step: 1950
ckpt_path: 'logs/${app.dataset_name}/${app.meta.model}/train-step${app.ckpt_step}.pth.tar'                       

logging:
  folder: 'logs/${app.dataset_name}/${app.meta.model}/eval/${app.ckpt_step}'     
  write_tag: AD               