# @package app
meta:
  model: 'dinov3'
  crop_size: 512
  pred_depth: 6
  pred_emb_dim: 384
  use_bfloat16: false
  if_pred_pe: false
  n_layer: 3

logging:
  folder: logs/${data.data_name}/${app.meta.model}${oc.select:diy_name,""}
  write_tag: train