# @package app
meta:
  model: 'dinov2'
  crop_size: 518
  pred_depth: 6
  pred_emb_dim: 384
  use_bfloat16: false

dataset_name: ${data.dataset}

logging:
  folder: logs/${app.dataset_name}/${app.meta.model}
  write_tag: train