# @package app
meta:
  model: 'dinov2'
  crop_size: 518
  pred_depth: 6
  pred_emb_dim: 384
  use_bfloat16: false

logging:
  folder: logs/${data.data_name}/${app.meta.model}${oc.select:diy_name,""}
  write_tag: train