# @package app
meta:
  model: 'clip'
  crop_size: 224
  pred_depth: 6
  pred_emb_dim: 384
  use_bfloat16: false
  n_layer: 3
  feat_normed: false
  loss_mode: 'l2'  # l2 or smooth_l1

logging:
  folder: logs/${data.data_name}/${app.meta.model}${oc.select:diy_name,""}
  write_tag: train