# configs/xxx.yaml
defaults:
  - _self_
  - app: train_dinov3 # merge/extend on top of app: default

# train / AD
mode: train

data:
  batch_size: 8
  num_workers: 0
  pin_mem: true
  dataset: mvtec
  data_name: fewshot-folder-name
  data_path: /path/to/fewshot-folder
  train_root: ${data.data_path}/${data.data_name}
  test_root: /path/to/dataset
  mvtec_classnames:                            
    - bottle
    - cable
    - capsule
    - carpet
    - grid
    - hazelnut
    - leather
    - metal_nut
    - pill
    - screw
    - tile
    - toothbrush
    - transistor
    - wood
    - zipper

  visa_classnames:                            
    - candle
    - capsules
    - cashew
    - chewinggum
    - fryum
    - macaroni1
    - macaroni2
    - pcb1
    - pcb2
    - pcb3
    - pcb4
    - pipe_fryum

optimization:
  epochs: 2000
  lr: 0.005
  weight_decay: 1e-4

testing:
  K_top_mvtec: 10    
  K_top_visa: 6         
  expect_fpr: 0.3     
  max_steps: 200      
  segmentation_vis: True

devices: [cuda:0]

dist:
  master_addr: localhost
  master_port: 40112
  backend: nccl

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
